- name: Deploy files
  shell: powershell
  run: |
    $src = "$env:GITHUB_WORKSPACE"
    $dst = "C:\inetpub\wwwroot\JConnect"

    New-Item -ItemType Directory -Path $dst -Force | Out-Null

    robocopy $src $dst /MIR /XD .git .github node_modules /R:2 /W:2
    $code = $LASTEXITCODE
    Write-Host "Robocopy exit code: $code"

    if ($code -ge 8) {
      Write-Error "Robocopy failed with exit code $code"
      exit $code         # ทำให้ workflow ล้มเหลวจริงเมื่อ error
    } else {
      Write-Host "Robocopy succeeded (robocopy exit code $code)"
      exit 0             # บังคับให้ step สำเร็จ
    }
