name: Deploy to Windows Server

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

defaults:
  run:
    shell: powershell   # <-- ใช้ Windows PowerShell 5.1 ที่มีอยู่แล้วบนเครื่อง

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64, prod]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy files
        run: |
          $src = "$env:GITHUB_WORKSPACE"
          $dst = "C:\inetpub\wwwroot\JConnect"
          New-Item -ItemType Directory -Path $dst -Force | Out-Null
          robocopy $src $dst /MIR /XD .git .github node_modules /R:2 /W:2
          $code = $LASTEXITCODE
          Write-Host "Robocopy exit code: $code"
          if ($code -ge 8) { throw "Robocopy failed with exit code $code" }

      - name: Recycle IIS App Pool
        run: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name "JConnectPool"
